export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
export const LOAD_QUOTES_SUCCESS = 'LOAD_QUOTES_SUCCESS';
export const GET_QUOTE_SUCCESS = 'GET_QUOTE_SUCCESS';
export const LOAD_UNDERWRITERS_SUCCESS = 'LOAD_UNDERWRITERS_SUCCESS';
